### ISSUE TITLE
files not find

### ISSUE THREAD

**Issue by lfs119** [TencentAI4S/HuDiff#4]
Hi,  Thanks for your awesome work.  there is a bug when running 'python patent_eval.py '   where can i get 'sample_t20_mou_score.csv'  and 'sample_t20_score.csv'

**Comment by waitma** [comment]
Apologies for the confusion. The two files, sample_t20_mou_score.csv and sample_t20_score.csv, can be obtained by running the T20 evaluation scripts. For convenience, we have already provided these files for HuAb348 and Humab25. You can find them in the data directory within their corresponding folders.
