### ISSUE TITLE
eval_abnativ_model = pretrained_model_list['abnativ'] err

### ISSUE THREAD

**Issue by kehan777** [TencentAI4S/HuDiff#5]
python nanobody_scripts/nanosample.py --ckpt checkpoints/nanobody/hudiffnb.pt --data_fpath data/nanobody_eval_data/abnativ_select_vhh.csv --model pretrain --inpaint_sample False

False
Initializing the abnativ score model and infilling model!
Traceback (most recent call last):
  File "nanobody_scripts/nanosample.py", line 255, in <module>
    model = model_selected(config).to(device)
  File "/mnt/d/conda/jupyter/HuDiff/utils/train_utils.py", line 53, in model_selected
    return NanoInfillingFramework(config.model, pretrained_model, tokenizer)
  File "/mnt/d/conda/jupyter/HuDiff/model/nanoencoder/model.py", line 355, in __init__
    self.eval_abnativ_model = pretrained_model_list['abnativ']
TypeError: 'NoneType' object is not subscriptable

Hello, please tell me how to solve the error above. 
I put the abnativ model in ./checkpoint/abnativ/vhh_model.ckpt, it is correct ?

**Comment by waitma** [comment]
> python nanobody_scripts/nanosample.py --ckpt checkpoints/nanobody/hudiffnb.pt --data_fpath data/nanobody_eval_data/abnativ_select_vhh.csv --model pretrain --inpaint_sample False
> 
> False Initializing the abnativ score model and infilling model! Traceback (most recent call last): File "nanobody_scripts/nanosample.py", line 255, in model = model_selected(config).to(device) File "/mnt/d/conda/jupyter/HuDiff/utils/train_utils.py", line 53, in model_selected return NanoInfillingFramework(config.model, pretrained_model, tokenizer) File "/mnt/d/conda/jupyter/HuDiff/model/nanoencoder/model.py", line 355, in **init** self.eval_abnativ_model = pretrained_model_list['abnativ'] TypeError: 'NoneType' object is not subscriptable
> 
> Hello, please tell me how to solve the error above. I put the abnativ model in ./checkpoint/abnativ/vhh_model.ckpt, it is correct ?

The error you're encountering indicates that the abnativ model parameter is not being correctly loaded, and the pretrained_model_list['abnativ'] is returning None, causing a TypeError. To address this, you can bypass loading the abnativ model by setting it to None in the code. This is because during inference, only the infilling part of the Hudiff-nb model is used, and the abnativ model is not required.
